"""added user_id

Revision ID: 1a6f6c65581b
Revises: 1dfaf5afde81
Create Date: 2021-08-08 09:30:04.901270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6f6c65581b'
down_revision = '1dfaf5afde81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_input',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('category_group_id', sa.String(length=64), nullable=True),
    sa.Column('category_name', sa.String(length=64), nullable=True),
    sa.Column('category_group_name', sa.String(length=64), nullable=True),
    sa.Column('ideal_contribution', sa.Float(), nullable=True),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('savings_contr', sa.Float(), nullable=True),
    sa.Column('fix_cat', sa.Float(), nullable=True),
    sa.Column('cat_group_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    with op.batch_alter_table('user_input', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_input_category_id'), ['category_id'], unique=True)

    op.drop_table('group_analysis')
    with op.batch_alter_table('budget_category_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('budget_group_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('budget_pacing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_pacing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('budget_group_analysis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('budget_category_analysis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('group_analysis',
    sa.Column('category_group_name', sa.TEXT(), nullable=True),
    sa.Column('spending_this_month', sa.FLOAT(), nullable=True),
    sa.Column('spending_this_month_perc', sa.FLOAT(), nullable=True),
    sa.Column('spending_last_month', sa.FLOAT(), nullable=True),
    sa.Column('spending_last_month_perc', sa.FLOAT(), nullable=True),
    sa.Column('budgeting_this_month', sa.FLOAT(), nullable=True),
    sa.Column('budgeting_this_month_perc', sa.FLOAT(), nullable=True),
    sa.Column('budgeting_last_month', sa.FLOAT(), nullable=True),
    sa.Column('budgeting_last_month_perc', sa.FLOAT(), nullable=True),
    sa.Column('spending_diff_mom', sa.FLOAT(), nullable=True),
    sa.Column('budgeting_diff_mom', sa.FLOAT(), nullable=True),
    sa.Column('ideal_contribution', sa.FLOAT(), nullable=True),
    sa.Column('ideal_contribution_perc', sa.FLOAT(), nullable=True),
    sa.Column('spending_3m_diff', sa.FLOAT(), nullable=True),
    sa.Column('budgeting_3m_diff', sa.FLOAT(), nullable=True)
    )
    with op.batch_alter_table('user_input', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_input_category_id'))

    op.drop_table('user_input')
    # ### end Alembic commands ###
