"""add user_id

Revision ID: 2d5a1d2e7439
Revises: 9e4fffb31257
Create Date: 2021-08-08 12:46:57.753642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5a1d2e7439'
down_revision = '9e4fffb31257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_category_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('None', 'users', ['user_id_number'], ['id'])

    with op.batch_alter_table('budget_group_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('None', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('budget_pacing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('None', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_pacing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('budget_group_analysis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('budget_category_analysis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id_number')

    # ### end Alembic commands ###
